In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
pd.set_option('display.max_columns', None)

In [7]:
df = pd.read_csv('weatherAUS.csv')
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  \
0           W           44.0          W        WNW          20.0   
1         WNW           44.0        NNW        WSW           4.0   
2         WSW           46.0          W        WSW          19.0   
3          NE           24.0         SE          E          11.0   
4           W           41.0        ENE         NW           7.0   

   WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  \
0          24.0         71.0         22.0       1007.7       1007.1       8.0   
1          22.0         44.0         25.0       1010.6       1007.8       NaN   
2          26.0         38.0         30.0       1007.6       1008.7       NaN   
3           9.0         45.0         16.0       1017.6       1012.8       NaN   
4          20.0         82.0         33.0       1010.8       1006.0       7.0   

   Cloud3pm  Temp9am  Temp3pm RainToday RainTomorrow  
0       NaN     16.9     21.8        No           No  
1       NaN     17.2     24.3        No           No  
2       2.0     21.0     23.2        No           No  
3       NaN     18.1     26.5        No           No  
4       8.0     17.8     29.7        No           No

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Date           145460 non-null  object 
 1   Location       145460 non-null  object 
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object 
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object 
 10  WindDir3pm     141232 non-null  object 
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null

In [9]:
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [10]:
df.dropna(subset=['RainTomorrow'], inplace=True)
df.isnull().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RainTomorrow         0
dtype: int64

In [11]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

Date: 3436
Location: 49
MinTemp: 389
MaxTemp: 505
Rainfall: 679
Evaporation: 356
Sunshine: 145
WindGustDir: 16
WindGustSpeed: 67
WindDir9am: 16
WindDir3pm: 16
WindSpeed9am: 43
WindSpeed3pm: 44
Humidity9am: 101
Humidity3pm: 101
Pressure9am: 546
Pressure3pm: 549
Cloud9am: 10
Cloud3pm: 10
Temp9am: 440
Temp3pm: 500
RainToday: 2
RainTomorrow: 2


In [12]:
from sklearn.preprocessing import LabelEncoder

lee = LabelEncoder()
for col in ['RainToday', 'RainTomorrow']:
    df[col] = lee.fit_transform(df[col])

In [13]:
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  \
0           W           44.0          W        WNW          20.0   
1         WNW           44.0        NNW        WSW           4.0   
2         WSW           46.0          W        WSW          19.0   
3          NE           24.0         SE          E          11.0   
4           W           41.0        ENE         NW           7.0   

   WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  \
0          24.0         71.0         22.0       1007.7       1007.1       8.0   
1          22.0         44.0         25.0       1010.6       1007.8       NaN   
2          26.0         38.0         30.0       1007.6       1008.7       NaN   
3           9.0         45.0         16.0       1017.6       1012.8       NaN   
4          20.0         82.0         33.0       1010.8       1006.0       7.0   

   Cloud3pm  Temp9am  Temp3pm  RainToday  RainTomorrow  
0       NaN     16.9     21.8          0             0  
1       NaN     17.2     24.3          0             0  
2       2.0     21.0     23.2          0             0  
3       NaN     18.1     26.5          0             0  
4       8.0     17.8     29.7          0             0

In [15]:
df['RainToday'].unique()

array([0, 1, 2])

In [16]:
df['RainTomorrow'].unique()

array([0, 1])

In [18]:
for col in ['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine','WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am','Temp3pm']:
    df[col] = df[col].fillna(df[col].mean())

In [19]:
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6     5.469824  7.624853   
1  2008-12-02   Albury      7.4     25.1       0.0     5.469824  7.624853   
2  2008-12-03   Albury     12.9     25.7       0.0     5.469824  7.624853   
3  2008-12-04   Albury      9.2     28.0       0.0     5.469824  7.624853   
4  2008-12-05   Albury     17.5     32.3       1.0     5.469824  7.624853   

  WindGustDir  WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  \
0           W           44.0          W        WNW          20.0   
1         WNW           44.0        NNW        WSW           4.0   
2         WSW           46.0          W        WSW          19.0   
3          NE           24.0         SE          E          11.0   
4           W           41.0        ENE         NW           7.0   

   WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  \
0          24.0         71.0         22.0       1007.7       1007.1  8.000000   
1          22.0         44.0         25.0       1010.6       1007.8  4.437189   
2          26.0         38.0         30.0       1007.6       1008.7  4.437189   
3           9.0         45.0         16.0       1017.6       1012.8  4.437189   
4          20.0         82.0         33.0       1010.8       1006.0  7.000000   

   Cloud3pm  Temp9am  Temp3pm  RainToday  RainTomorrow  
0  4.503167     16.9     21.8          0             0  
1  4.503167     17.2     24.3          0             0  
2  2.000000     21.0     23.2          0             0  
3  4.503167     18.1     26.5          0             0  
4  8.000000     17.8     29.7          0             0

In [20]:
df.describe()

MinTemp        MaxTemp       Rainfall    Evaporation  \
count  142193.000000  142193.000000  142193.000000  142193.000000   
mean       12.186400      23.226784       2.349974       5.469824   
std         6.388924       7.109554       8.423217       3.168114   
min        -8.500000      -4.800000       0.000000       0.000000   
25%         7.600000      17.900000       0.000000       4.000000   
50%        12.000000      22.700000       0.000000       5.469824   
75%        16.800000      28.200000       0.800000       5.469824   
max        33.900000      48.100000     371.000000     145.000000   

            Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  142193.000000  142193.000000  142193.000000  142193.000000   
mean        7.624853      39.984292      14.001988      18.637576   
std         2.734927      13.138385       8.851082       8.721551   
min         0.000000       6.000000       0.000000       0.000000   
25%         7.624853      31.000000       7.000000      13.000000   
50%         7.624853      39.000000      13.000000      18.637576   
75%         8.700000      46.000000      19.000000      24.000000   
max        14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm    Pressure9am    Pressure3pm  \
count  142193.000000  142193.000000  142193.000000  142193.000000   
mean       68.843810      51.482606    1017.653758    1015.258204   
std        18.932077      20.532065       6.746248       6.681788   
min         0.000000       0.000000     980.500000     977.100000   
25%        57.000000      37.000000    1013.500000    1011.000000   
50%        70.000000      51.482606    1017.653758    1015.258204   
75%        83.000000      65.000000    1021.800000    1019.400000   
max       100.000000     100.000000    1041.000000    1039.600000   

            Cloud9am       Cloud3pm        Temp9am        Temp3pm  \
count  142193.000000  142193.000000  142193.000000  142193.000000   
mean        4.437189       4.503167      16.987509      21.687235   
std         2.278080       2.104709       6.472166       6.870771   
min         0.000000       0.000000      -7.200000      -5.400000   
25%         3.000000       4.000000      12.300000      16.700000   
50%         4.437189       4.503167      16.800000      21.300000   
75%         6.000000       6.000000      21.500000      26.300000   
max         9.000000       9.000000      40.200000      46.700000   

           RainToday   RainTomorrow  
count  142193.000000  142193.000000  
mean        0.240989       0.224181  
std         0.450212       0.417043  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.000000       0.000000  
75%         0.000000       0.000000  
max         2.000000       1.000000

In [24]:
from sklearn.preprocessing import StandardScaler

numerical_features = ['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine','WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am','Temp3pm']

scaler = StandardScaler()

df[numerical_features] = scaler.fit_transform(df[numerical_features])

df.describe()

MinTemp       MaxTemp      Rainfall   Evaporation      Sunshine  \
count  1.421930e+05  1.421930e+05  1.421930e+05  1.421930e+05  1.421930e+05   
mean   2.238670e-17  2.558480e-17 -2.598456e-17 -1.279240e-17 -2.287171e-17   
std    1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00   
min   -3.237865e+00 -3.942143e+00 -2.789887e-01 -1.726530e+00 -2.787964e+00   
25%   -7.178699e-01 -7.492457e-01 -2.789887e-01 -4.639446e-01 -1.788028e-16   
50%   -2.917555e-02 -7.409551e-02 -2.789887e-01  1.103344e-16 -1.788028e-16   
75%    7.221273e-01  6.995141e-01 -1.840128e-01  1.103344e-16  3.931185e-01   
max    3.398644e+00  3.498574e+00  4.376610e+01  4.404218e+01  2.513840e+00   

       WindGustSpeed  WindSpeed9am  WindSpeed3pm   Humidity9am   Humidity3pm  \
count   1.421930e+05  1.421930e+05  1.421930e+05  1.421930e+05  1.421930e+05   
mean    1.129329e-17  1.599050e-18  1.679002e-17  3.198099e-18 -3.198099e-17   
std     1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00   
min    -2.586651e+00 -1.581958e+00 -2.136964e+00 -3.636371e+00 -2.507433e+00   
25%    -6.838225e-01 -7.910912e-01 -6.463983e-01 -6.255971e-01 -7.053678e-01   
50%    -7.491751e-02 -1.132055e-01 -1.679002e-17  6.107062e-02  7.221351e-17   
75%     4.578744e-01  5.646801e-01  6.148497e-01  7.477383e-01  6.583576e-01   
max     7.231942e+00  1.310556e+01  7.838361e+00  1.645688e+00  2.363014e+00   

        Pressure9am   Pressure3pm      Cloud9am      Cloud3pm       Temp9am  \
count  1.421930e+05  1.421930e+05  1.421930e+05  1.421930e+05  1.421930e+05   
mean  -1.599050e-17 -1.758955e-17  4.237482e-17  7.995249e-18  1.918860e-17   
std    1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00   
min   -5.507341e+00 -5.710798e+00 -1.947782e+00 -2.139575e+00 -3.737171e+00   
25%   -6.157160e-01 -6.372873e-01 -6.308796e-01 -2.390681e-01 -7.242591e-01   
50%    1.490794e-14  1.643218e-15  1.471126e-16  1.294413e-17 -2.897164e-02   
75%    6.146018e-01  6.198657e-01  6.860233e-01  7.111855e-01  6.972175e-01   
max    3.460638e+00  3.643019e+00  2.002926e+00  2.136566e+00  3.586523e+00   

            Temp3pm      RainToday   RainTomorrow  
count  1.421930e+05  142193.000000  142193.000000  
mean   3.517909e-17       0.240989       0.224181  
std    1.000004e+00       0.450212       0.417043  
min   -3.942400e+00       0.000000       0.000000  
25%   -7.258651e-01       0.000000       0.000000  
50%   -5.635995e-02       0.000000       0.000000  
75%    6.713630e-01       0.000000       0.000000  
max    3.640473e+00       2.000000       1.000000

In [26]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import accuracy_score, classification_report
from tqdm import tqdm

In [29]:
X = df.drop(['RainTomorrow','Date','Location','WindGustDir', 'WindDir9am','WindDir3pm'], axis=1).values
y = df['RainTomorrow'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, shuffle=True, random_state=42)

In [30]:
X_train.shape

(113754, 17)

In [31]:
X_test.shape

(28439, 17)

In [32]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

In [34]:
X_train_tensor

tensor([[ 1.1134e+00,  1.6278e+00, -2.7899e-01,  ...,  1.1298e+00,
          1.7338e+00,  0.0000e+00],
        [-1.6630e-16,  2.2387e-16, -2.5524e-01,  ...,  3.4220e-16,
         -3.6357e-16,  0.0000e+00],
        [ 1.2735e-01,  2.4364e-02, -2.7899e-01,  ..., -9.0775e-02,
          2.0562e-01,  0.0000e+00],
        ...,
        [-4.5178e-01, -9.8836e-01,  1.9589e-01,  ..., -3.3799e-01,
         -3.6357e-16,  1.0000e+00],
        [ 3.9343e-01,  1.0090e+00, -2.7899e-01,  ...,  8.6718e-01,
          9.3334e-01,  0.0000e+00],
        [ 5.4995e-01,  4.4633e-01, -2.7899e-01,  ...,  6.1996e-01,
          6.5681e-01,  0.0000e+00]])

In [35]:
y_train_tensor

tensor([[0.],
        [0.],
        [0.],
        ...,
        [1.],
        [0.],
        [0.]])

In [36]:
from torch.utils.data import DataLoader, TensorDataset
train_data = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(dataset=train_data, batch_size=64, shuffle=True)

In [37]:
train_loader

In [38]:
import torch.nn as nn

input_size = 17
hidden_size = 10
output_size = 1

model = nn.Sequential(
    nn.Linear(input_size, hidden_size),
    nn.ReLU(),
    nn.Linear(hidden_size, hidden_size),
    nn.ReLU(),
    nn.Linear(hidden_size, output_size),
    nn.Sigmoid()
)

loss_function = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
epochs = 10

for epoch in tqdm(range(epochs)):
    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_X)
        batch_y = batch_y.clamp(0, 1)
        loss = loss_function(outputs, batch_y)
        loss.backward()
        optimizer.step()

with torch.no_grad():
    predictions = model(X_test_tensor)
    predicted_classes = (predictions > 0.5).int().numpy()

100%|██████████| 10/10 [00:28<00:00,  2.86s/it]
