In [2]:
import numpy as np

Question 1

In [1]:
vector = list(range(15, 56))

print(vector[1:-1])

[16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]


Question 2

In [5]:
array = np.full((3, 4), 5)

print(array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Question 3

In [6]:
matrix = np.arange(10, 19).reshape(3, 3)

print(matrix)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


Question 4

In [7]:
matrix = np.diag([1, 2, 3, 4, 5])

print(matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Question 5

In [9]:
vector = np.zeros(10)

vector[5] = 11

vector

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

Question 6

In [10]:
array = np.array([1, 2, 3, 4, 5])

float_array = np.asfarray(array)

float_array

array([1., 2., 3., 4., 5.])

Question 7

In [11]:
array = np.array([[0, 1, 2, 3],
                  [4, 5, 6, 7],
                  [8, 9, 10, 11]])


new_array = array[:, ::-1]

new_array

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

Question 8

In [15]:
array = np.array(["Hello", "World", "PyThOn"])

capitalized = np.char.capitalize(array)
lowercased = np.char.lower(array)
uppercased = np.char.upper(array)
swapcased = np.char.swapcase(array)
titlecased = np.char.title(array)

print("Original Array:", array)
print("Capitalized:", capitalized)
print("Lowercased:", lowercased)
print("Uppercased:", uppercased)
print("Swapcased:", swapcased)
print("Titlecased:", titlecased)

Original Array: ['Hello' 'World' 'PyThOn']
Capitalized: ['Hello' 'World' 'Python']
Lowercased: ['hello' 'world' 'python']
Uppercased: ['HELLO' 'WORLD' 'PYTHON']
Swapcased: ['hELLO' 'wORLD' 'pYtHoN']
Titlecased: ['Hello' 'World' 'Python']


Question 9

In [18]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Today:", today)
print("Yesterday:", yesterday)
print("Tomorrow:", tomorrow)

Today: 2025-04-22
Yesterday: 2025-04-21
Tomorrow: 2025-04-23


Question 10

In [19]:
array = np.array([10, 20, 30])

append = [40, 50, 60, 70, 80, 90]

updated = np.append(array, append)

print(updated)

[10 20 30 40 50 60 70 80 90]
